###Journals Index 
GET http://localhost:3000/journals

### Journals Create 
POST http://localhost:3000/journals
Content-Type: application/json

{
  "name": "It has been a hell of a week!"
}

### Journal_Entries Index 
GET http://localhost:3000/journal-entries


###Journal_Entries Show
GET http://localhost:3000/journal-entries/1

###Journal_Entries Create 
POST http://localhost:3000/journal-entries
Content-Type: application/json

{
  "title": "Friday, capstone day!!!!",
  "text": "Today is friday, August 26, and it is capstone day, I am still working on my backend because somehow I managed to break it, and decided it was best to just restart the whole thing"
}

### User Sign up (create action)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Sheykly",
  "email": "sheykly@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "sheykly@example.com",
  "password": "password"
}

@jwt_sheykly = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MzAzMzh9.eTG0dpg4aMuHRq0NmVLObbI_lF_1SIsi5XOXoPcDXH8

### User Sign up (create action)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Parker",
  "email": "parker@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "parker@example.com",
  "password": "password"
}
####

@jwt_parker = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE2MzUzOTR9.WxNlvsLTEV3EVaKN7Ukw1Bc1-peMaBcwUPLvtJ7rzmY


### Journals create
POST http://localhost:3000/journals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MzAzMzh9.eTG0dpg4aMuHRq0NmVLObbI_lF_1SIsi5XOXoPcDXH8
Content-Type: application/json

{
  "name": "End of the Month Reflections"
}
######################################################################################################
# just more data

###Journal_Entries Create 
POST http://localhost:3000/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MzAzMzh9.eTG0dpg4aMuHRq0NmVLObbI_lF_1SIsi5XOXoPcDXH8
Content-Type: application/json

{
  "title": "Saturday, just another day",
  "text": "Today is Saturday, August 27th, and it is just another day. I have lots of homework that I do not want to get to"
}

###
POST http://localhost:3000/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MzAzMzh9.eTG0dpg4aMuHRq0NmVLObbI_lF_1SIsi5XOXoPcDXH8
Content-Type: application/json

{
  "title": "Saturday, just another day",
  "text": "Today is Saturday, August 27th, and it is just another day. I have lots of homework that I do not want to get to"
}

###
POST http://localhost:3000/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MzAzMzh9.eTG0dpg4aMuHRq0NmVLObbI_lF_1SIsi5XOXoPcDXH8
Content-Type: application/json

{
  "title": "Sunday, the last day of the weekend",
  "text": "Today is Sunday, August 28th, I feel like being lazy before starting the week."
}

###
POST http://localhost:3000/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MzAzMzh9.eTG0dpg4aMuHRq0NmVLObbI_lF_1SIsi5XOXoPcDXH8
Content-Type: application/json

{
  "title": "Monday, just another day",
  "text": "Today is Monday, August 29th, ugh, Mondays. What can I say about it."
}

###
POST http://localhost:3000/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MzAzMzh9.eTG0dpg4aMuHRq0NmVLObbI_lF_1SIsi5XOXoPcDXH8
Content-Type: application/json

{
  "title": "Tuesday, Almost the middle of the week!",
  "text": "Today is Tuesday, August 30th, ugh, I had four classes, yay!"
}

###
POST http://localhost:3000/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NjE2MzAzMzh9.eTG0dpg4aMuHRq0NmVLObbI_lF_1SIsi5XOXoPcDXH8
Content-Type: application/json

{
  "title": "Wednesday, Wednedays!! My magical days!",
  "text": "I am looking forward to magic club, I will get to show my very own stack to the group"
}

### Journals create
POST http://localhost:3000/journals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE2MzM3MzZ9.S2EwOHCY1R4TUDc5RgHVmp0oWWckdniCOEc4jBCHFnM
Content-Type: application/json

{
  "name": "Just my kitchen encounters"
}

### Journals create
POST http://localhost:3000/journals
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE2MzM3MzZ9.S2EwOHCY1R4TUDc5RgHVmp0oWWckdniCOEc4jBCHFnM
Content-Type: application/json

{
  "name": "My everyday, not much"
}

###
POST http://localhost:3000/journal-entries
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NjE2MzUzOTR9.WxNlvsLTEV3EVaKN7Ukw1Bc1-peMaBcwUPLvtJ7rzmY
Content-Type: application/json

{
  "title": "Sanwich!",
  "text": "I got out of bed and made a sandwich."
}